mod arithmetic_expression;
pub mod arithmetic_instruction;
pub mod assembly;
pub mod boolean_instruction;
pub mod computer;
pub mod effective_address;
pub mod inc_instruction;
pub mod instruction;
pub mod jump_instruction;
pub mod move_instruction;
pub mod program;
pub mod register;
pub mod trivia_instruction;
