[package]
name = "sim_8086"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
const_panic = "0.2.7"
nom = "7.1.3"
